services:
  - type: web
    name: square-auctions
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PUBLIC_BASE_URL
        sync: false
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: SQUARE_LOCATION_ID
        sync: false
      - key: SQUARE_ENVIRONMENT
        value: sandbox
      - key: DATABASE_URL
        fromDatabase:
          name: square-auctions-db
          property: connectionString

databases:
  - name: square-auctions-db
    plan: free
