services:
  - type: web
    name: square-auctions
    env: node
    plan: free
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: auctions-db
          property: connectionString
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: SQUARE_ENVIRONMENT
        sync: false
      - key: SQUARE_LOCATION_ID
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
      - key: ALERT_EMAIL_TO
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
databases:
  - name: auctions-db
    plan: free